services:
  network-api:
    build:
      context: .
      dockerfile: NetworkEdition.API/Dockerfile
    ports:
      - "5000:80"
  
  presentation:
    build:
      context: .
      dockerfile: Presentation/Dockerfile
    ports:
      - "8080:80"
    depends_on: 
      - network-api
    command:
      - "http://localhost:5000/api/"
