services:
  sensor-edition-api:
    build:
      context: .
      dockerfile: NetworkEdition.API/Dockerfile
    ports:
      - "5000:80"
  presentation:
    build:
      context: .
      dockerfile: Presentation/Dockerfile
    ports:
      - "8080:80"
    depends_on: 
      - sensor-edition-api
    environment:
      - "NETWORK_EDITION_URL=http://localhost:5000"
